### ISSUE TITLE
Continuous Integration Error Output

### ISSUE THREAD

**Issue by Hapaxia** [Hapaxia/SelbaWard#42]
The CI tests are outputting errors.

One such error is CMake-based:
```
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
```

**Comment by eXpl0it3r** [comment]
I think for Windows images you now have to install it explicitly. Paging CI master @ChrisThrasher 😄

**Comment by ChrisThrasher** [comment]
More GitHub nonsense because they removed Ninja from their Windows images. The solution is to install Ninja. SFML does that here:
https://github.com/SFML/SFML/blob/5b609056894895f1241a6d41df51a5830740ea2b/.github/workflows/ci.yml#L82-L86

I'd recommend adding this to your CI script:
```yaml
    - name: Get CMake and Ninja
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: 3.22
        ninjaVersion: latest
```
